services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qr-iorana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_PATH=/app/data/qr.db
      - ALLOWED_ORIGIN=https://qr.iorana.dev
    volumes:
      - qr-db-data:/app/data

volumes:
  qr-db-data:
    driver: local
